- name: check if node exporter exist
  stat:
    path: "{{ node_exporter_bin }}"
  register: __check_node_exporter_present

- name: Remove the user 'node_exporter_user'
  ansible.builtin.user:
    name: "{{ node_exporter_user }}"
    state: absent
    remove: yes

- name: Stop service node_exporter on debian, if running
  ansible.builtin.systemd:
    name: node_exporter
    state: stopped
    enabled: no

- name: clean service file
  file:
    path: /etc/systemd/system/node_exporter.service
    state: absent

- name: clean data dirs
  file:
    path: "{{ node_exporter_dir_conf }}"
    state: absent
