---
servers:
  hosts:
    10.80.10.223
    52.35.103.6
    44.224.135.182

# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: servers
  become: yes

  tasks:

- name: Call Roles
  hosts: servers
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   - motd
