apiVersion: v1
kind: Pod
metadata:
  name: nginx-web
spec:
  containers:
    - name: nginx-web
      image: nginx:1.9
      ports:
        - containerPort: 80
          name: web
      volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: nginx-pvc
  volumes:
    - name: nginx-pvc
      persistentVolumeClaim:
        # PVC name you created
        claimName: web-provisioner
