---
kind: Service
apiVersion: v1
metadata:
  name: blackbox
  namespace: blackbox
  labels:
    app: blackbox
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9115
      protocol: TCP
  selector:
    app: blackbox
