# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: all
  become: true

  tasks:

- name: Call Roles - SystemAdmin, Installations, Configurations & administration monitoring agents & clients
  hosts: all
  become: true
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   #- dockerhost
   #- lemp
   #- nginx
   #- apache2
   #- mysql
   - motd
   #- node-exporter


# - name: Master/Slave roles e.g mysql
#   hosts: all
#   become: yes
#   tasks:
#     - include_role:
#         name: mysql
#         tasks_from: master

- name: UnInstall roles e.g motd, node_exporter & nginx
  hosts: all
  become: true
  tasks:
    - include_role:
        name: motd
        # tasks_from: uninstall

- name: Apache2 Multiple entries in vhosts
  hosts: all
  vars_files:
   - roles/apache2/vars/main.yml
  become: true
  roles:
   - apache2
