---

- name: Remove centos packaged docker
  yum:
    name: docker
    state: absent

- name: Install Docker
  yum:
    name: "{{ docker_pkg_name }}"
    state: "{{ docker_pkg_state }}"
    disable_gpg_check: no

- name: Install Docker Python Module
  yum:
    name: "{{ docker_py_pkg_name | default('python-docker-py') }}"
    state: "{{ docker_py_pkg_state | default('latest') }}"
    disable_gpg_check: no
  when:
    - docker_install_py_module
