---

- name: Install Official Docker Repositories (redhat)
  yum_repository:
    name: "docker-ce-{{ item.channel }}"
    description: Docker Repository Stable Channel
    baseurl: "https://download.docker.com/linux/centos/7/$basearch/{{ item.channel }}"
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: true
    enabled: "{{ item.enabled }}"
  with_items:
    - channel: stable
      enabled: "{{ docker_repo_channel_stable_enabled }}"
    - channel: edge
      enabled: "{{ docker_repo_channel_edge_enabled }}"
    - channel: test
      enabled: "{{ docker_repo_channel_test_enabled }}"
  when:
    - docker_repo_enabled
