---
plugin: aws_ec2
boto_profile: default

regions:
  - us-east-1

filters:
  # All instances with their state as `running`
  instance-state-name: running
keyed_groups:
  - prefix: tag
    key: tags
compose:
  ansible_host: public_dns_name
